# Generated by Django 3.2.2 on 2021-06-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voters',
            name='age',
            field=models.IntegerField(),
        ),
    ]
