# Generated by Django 3.2.2 on 2021-06-30 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0002_alter_voters_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voters',
            name='status',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1),
        ),
    ]
